In [1]:
import pandas as pd
import numpy as np
import math
from sklearn.model_selection import train_test_split
from sklearn import svm
pd.set_option('display.max_columns', None)
pd.options.mode.chained_assignment = None  # default='warn'

ModuleNotFoundError: No module named 'sklearn'

In [2]:
def raw_2080(rating):
    new = ((5 * rating) / (50/3))+20
    return new

def convert_2080_120(rating):
    new = math.ceil((round(((50/3) * (float(rating) - 20))/5,0))/10)
    return new

def convert_sbc_2080(rating):
    new = round((50 * (rating)/16.67)+20,0)
    return new

def convert_sbc_raw(rating):
    twenty = round((50 * (rating)/16.67)+20,0)
    raw = (((50/3) * (twenty - 20) )/ 5)
    return raw

In [3]:
convert_sbc_raw(6)

60.0

In [4]:
pool = pd.read_csv('C:/Users/night/draftpool.csv')
value = pd.read_csv('C:/Users/night/OneDrive/Documents/Out of the Park Developments/OOTP Baseball 22/saved_games/SBC.lg/import_export/csv/players_value.csv')
#pool = pool.merge(value[['player_id','oa', 'pot']], left_on = 'ID', right_on = 'player_id')

In [6]:
value.sample(5)

,player_id,team_id,league_id,position,role,offensive_value,offensive_value_talent,offensive_value_vsl,offensive_value_vsr,pitching_value,pitching_value_talent,pitching_value_vsl,pitching_value_vsr,overall_value,talent_value,career_value,leadoff_value_vsl,leadoff_value_vsr,running_value,stealing_value,season_performance,stats_value_0,stats_value_1,stats_value_2,stats_mod_0,stats_mod_1,stats_mod_2,ratings_value,overall_sp,overall_rp,overall_c,overall_1b,overall_2b,overall_3b,overall_ss,overall_lf,overall_cf,overall_rf,award_bat,award_pit,award_field,oa,pot
10720,43878,162,147,3,0,1006,908,802,1088,0,0,0,0,929,893,911,303,344,36,3,2.2000,1021,692,462,80,100,100,968,1,1,850,929,850,850,850,850,850,850,30.8628,0.0000,568.0256,37,37
4433,28571,253,154,1,12,500,467,500,500,134,509,111,143,369,509,439,238,238,26,0,-6.9752,0,170,0,0,77,0,411,217,88,367,369,367,367,367,367,367,367,0.0000,-14.2204,621.4038,20,20
18224,51408,404,160,8,0,34,669,76,27,0,90,0,0,1,740,372,231,218,136,17,-0.0686,0,0,0,0,0,0,28,1,1,1,1,1,1,1,1,1,1,0.0000,0.0000,586.2751,20,24
13094,46277,229,152,3,0,936,688,957,930,0,0,0,0,842,596,719,284,281,67,3,0.5830,0,0,1009,0,0,53,772,1,1,838,842,838,838,838,838,838,838,0.0000,0.0000,400.0000,32,32
4801,32507,0,0,1,12,132,240,133,132,0,278,0,0,91,170,346,159,159,16,0,4.8416,0,0,0,0,0,0,108,414,91,32,32,32,32,32,32,32,32,0.0000,0.0000,0.0000,20,20

In [172]:
convert_sbc_2080(13)

59.0



$ {sbcrating} = \frac {16.67 * ({2080 rating} - 20)}{50}$

$ {11.669} = \frac {16.67 * ({55} - 20)}{50}$

$ {2080 rating} = \frac {50*sbcrating}{16.67} + 20$

$ 55.99 = \frac {50*12}{16.67} + 20$

$ 55 = \frac {50*11.669}{16.67} + 20$

In [173]:
batter_columns = ['ID', 'Name', 'Pos', 'Age', 'Height', 'Bats', 'Throws','PotCntct', 'PotGap', 'PotPow', 'PotEye', 'PotKs', 
'IFR', 'IFE', 'IFA', 'TDP', 'OFR', 'OFE', 'OFA', 'CAb', 'CArm', 'P', 'C', '1B', '2B', '3B', 'SS', 'LF', 
'CF', 'RF', 'Speed', 'Steal', 'Run', 'SacBunt', 'BuntHit','Int', 'WrkEthic', 'Greed', 'Loy', 'Lead', 'oa', 'pot']

pitcher_columns = ['ID', 'Name', 'Pos', 'Age', 'Height', 'Bats', 'Throws','PotStf', 'PotMov','PotCtrl', 'P','PotFst', 'PotSnk', 
'PotCutt', 'PotCrv', 'PotSld', 'PotChg', 'PotSplt', 'PotFrk', 'PotCirChg', 'PotScr', 'PotKncrv', 
'PotKnbl', 'Vel', 'GB', 'Stm', 'Hold','Int', 'WrkEthic', 'Greed', 'Loy', 'Lead', 'oa', 'pot']


two_way_columns = ['ID', 'Name', 'Pos', 'Age', 'Height', 'Bats', 'Throws', 'PotCntct', 'PotGap', 
'PotPow', 'PotEye', 'PotKs','IFR', 'IFE', 'IFA', 'TDP', 'OFR', 'OFE', 'OFA', 
'CAb', 'CArm', 'P', 'C', '1B', '2B', '3B', 'SS', 'LF', 'CF', 'RF', 
'Speed', 'Steal', 'Run', 'SacBunt', 'BuntHit', 'Stf', 'Mov', 'Ctrl', 'PotStf', 'PotMov',
'PotCtrl', 'Vel', 'GB', 'Stm', 'Hold', 'PotFst',
'PotSnk', 'PotCutt', 'PotCrv', 'PotSld', 'PotChg', 'PotSplt', 'PotFrk',
'PotCirChg', 'PotScr', 'PotKncrv', 'PotKnbl', 'Int', 'WrkEthic',
'Greed', 'Loy', 'Lead', 'oa', 'pot']

batters = pool[batter_columns]
pitchers = pool[pitcher_columns]
two_way = pool[two_way_columns]

In [174]:
pitchers.loc[:,'Total Pitches'] = pitchers[['PotFst', 'PotSnk', 'PotCutt', 'PotCrv', 'PotSld', 'PotChg', 'PotSplt', 'PotFrk', 'PotCirChg', 'PotScr', 'PotKncrv', 'PotKnbl']].astype(bool).sum(axis=1)

In [86]:
pitchers[pitchers['Pos'] == 'SP'].head()

,ID,Name,Pos,Age,Height,Bats,Throws,PotStf,PotMov,PotCtrl,P,PotFst,PotSnk,PotCutt,PotCrv,PotSld,PotChg,PotSplt,PotFrk,PotCirChg,PotScr,PotKncrv,PotKnbl,Vel,GB,Stm,Hold,Int,WrkEthic,Greed,Loy,Lead,oa,pot,Total Pitches
1,35785,Jorge Acevedo,SP,16,193,R,R,9,5,8,10,10,0,0,0,13,2,0,0,0,0,0,0,86-88,53,10,5,N,L,N,N,N,20,20,3
5,37941,Chad Adekunle,SP,20,184,L,L,9,6,9,8,10,0,0,10,4,10,0,0,0,0,0,0,89-91,49,12,19,N,L,N,L,L,20,20,4
9,26042,Juan Aguilar,SP,21,188,L,L,12,14,9,9,0,13,0,13,0,0,0,0,14,0,0,0,89-91,63,15,12,N,H,N,N,N,20,38,3
10,25018,Juan Aguilera,SP,17,189,R,R,9,4,6,6,12,0,0,0,8,7,0,6,0,0,0,0,90-92,49,13,9,N,L,N,H,L,20,20,4
21,23483,Rogelio Alvarado,SP,21,186,S,R,14,12,14,7,15,0,0,0,17,15,0,0,0,0,0,0,92-94,57,16,16,N,N,N,N,N,30,51,3

In [177]:
batters[~(batters['Pos'].isin(['SP','RP','CL']))]

,ID,Name,Pos,Age,Height,Bats,Throws,PotCntct,PotGap,PotPow,PotEye,PotKs,IFR,IFE,IFA,TDP,OFR,OFE,OFA,CAb,CArm,P,C,1B,2B,3B,SS,LF,CF,RF,Speed,Steal,Run,SacBunt,BuntHit,Int,WrkEthic,Greed,Loy,Lead,oa,pot
0,43713,Chris Abraham,3B,22,185,R,R,9,9,1,9,13,9,10,16,6,6,12,16,1,1,0,0,0,0,4,0,0,0,0,5,10,13,12,6,N,L,N,N,N,20,23
2,22930,Dan Adams,LF,21,185,L,L,13,15,6,7,19,8,6,1,1,9,10,5,1,1,0,0,0,0,0,0,7,0,0,19,18,18,9,7,L,N,H,N,N,20,28
4,47232,Sam Adams,RF,18,188,R,R,8,9,4,11,9,7,4,9,4,11,11,16,1,1,0,0,0,0,0,0,0,2,4,10,10,12,11,1,H,H,N,N,N,20,20
8,32880,Jonathan Agee,LF,20,193,R,R,7,9,3,11,8,3,3,10,2,8,9,15,1,1,0,0,0,0,0,0,3,0,0,8,15,14,10,1,N,L,N,N,N,20,20
12,34665,Danny Aikens,LF,20,179,R,R,9,10,6,11,10,7,4,7,5,12,8,9,1,1,0,0,3,0,0,0,10,2,4,13,3,2,7,10,N,L,N,N,N,20,20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1043,35347,Jamie Young,SS,20,194,R,R,9,9,5,11,10,14,17,15,18,5,13,16,1,1,0,0,0,0,0,11,0,0,0,19,10,8,11,10,N,N,H,N,N,20,38
1044,30961,Joe Young,LF,18,197,R,R,9,10,7,11,10,7,5,15,5,9,9,16,1,1,0,0,4,0,2,0,4,0,2,5,8,5,8,1,N,N,N,N,N,20,20
1045,31743,Robbie Young,C,19,183,R,R,8,10,6,12,8,4,4,4,2,3,5,3,12,6,0,3,1,0,0,0,0,0,0,2,5,8,8,4,N,L,H,L,L,20,31
1046,50270,Vic Young,C,22,188,R,R,8,9,5,12,7,3,8,12,2,4,5,11,11,15,0,5,0,0,0,0,0,0,0,1,3,1,11,2,N,N,H,N,L,20,33
1048,34864,Juan Zavaleta,CF,20,179,R,R,10,10,4,11,10,14,9,12,9,17,16,17,1,1,0,0,3,0,0,0,8,13,7,20,12,14,19,18,N,H,N,L,N,20,34