In [119]:
path = 'C:/Users/night/OneDrive/Documents/Out of the Park Developments/OOTP Baseball 22/saved_games/SBC.lg/import_export/csv/'

In [120]:
batters = pd.read_csv(path + 'players_career_batting_stats.csv')
season = 2043

In [125]:
def prep_batters(df):
    data = df.copy()
    data = data[(data['league_id'] == 145) & (data['split_id'] == 1) & (data['year'] >= (season - 3)) & (data['year'] < season) & (data['pa'] >= data.pa.quantile(0.7))]
    columns = ['player_id','ab', 'h', 'k', 'pa', 'pitches_seen', 'g', 'gs',
       'd', 't', 'hr', 'r', 'rbi', 'sb', 'cs', 'bb', 'ibb', 'gdp', 'sh', 'sf']
    return data[columns].groupby('player_id').mean().astype(int).reset_index()

In [126]:
batters = prep_batters(batters)

In [128]:
batters.sample(10)

,player_id,ab,h,k,pa,pitches_seen,g,gs,d,t,hr,r,rbi,sb,cs,bb,ibb,gdp,sh,sf
304,40257,303,68,104,338,1289,107,73,11,2,11,44,36,10,4,28,1,3,2,2
241,38042,349,75,113,427,1828,123,99,15,1,21,56,61,0,0,65,4,5,1,5
469,45713,573,164,128,619,2254,154,146,39,5,17,78,81,9,1,38,1,9,1,2
106,24112,507,146,93,566,2127,133,124,30,4,17,84,70,7,1,50,2,11,1,4
496,48596,340,109,31,380,1342,91,85,17,3,2,52,28,1,2,30,0,3,5,1
41,19516,551,142,128,638,2552,147,143,27,0,26,79,87,0,0,74,3,13,0,6
308,40343,579,165,111,625,2202,151,147,31,2,12,76,74,10,1,35,2,14,2,3
165,32974,477,138,97,508,1779,133,121,33,0,9,51,48,0,0,25,1,14,4,2
292,39881,202,47,55,230,907,59,58,8,0,7,30,28,0,0,18,0,4,2,0
197,35555,446,104,185,493,1927,116,110,15,4,16,63,55,16,8,35,0,3,3,2